"""added updated_at to shop model

Revision ID: 03088577b8b1
Revises: f14033aa0f94
Create Date: 2025-09-29 09:54:21.987904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03088577b8b1'
down_revision: Union[str, None] = 'f14033aa0f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'updated_at')
    # ### end Alembic commands ###
