"""Initial migration for new DB14

Revision ID: 0a1a37dc8d9d
Revises: 9c4138172206
Create Date: 2025-02-21 16:29:29.711487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1a37dc8d9d'
down_revision: Union[str, None] = '9c4138172206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
