"""Initial migration for new DB10

Revision ID: 0a2b7d0b0c23
Revises: 42e5c780fb93
Create Date: 2025-02-20 16:37:33.925855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2b7d0b0c23'
down_revision: Union[str, None] = '42e5c780fb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
