"""update4

Revision ID: 1e550f14e87a
Revises: 0f4286165387
Create Date: 2025-01-08 13:17:14.852751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e550f14e87a'
down_revision: Union[str, None] = '0f4286165387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.drop_constraint('appointment_appointment_id_fkey', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'doctor', ['doctor_id'], ['id'])
    op.drop_column('appointment', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_appointment_id_fkey', 'appointment', 'appointment', ['appointment_id'], ['id'])
    op.drop_column('appointment', 'doctor_id')
    # ### end Alembic commands ###
