"""Initial migration for new DB12

Revision ID: 249e7a2b77fd
Revises: 9b42e0f38f38
Create Date: 2025-02-20 16:44:18.560670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249e7a2b77fd'
down_revision: Union[str, None] = '9b42e0f38f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
