"""Initial migration for new DB10

Revision ID: 3be1c21ce391
Revises: b820f7a4b4a0
Create Date: 2025-02-20 16:04:00.544052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be1c21ce391'
down_revision: Union[str, None] = 'b820f7a4b4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
