"""Initial migration for new DB8

Revision ID: 4af0aa697edc
Revises: 4d23171cdd8b
Create Date: 2025-02-20 15:28:24.941704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af0aa697edc'
down_revision: Union[str, None] = '4d23171cdd8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
