"""Initial migration for new DB6

Revision ID: 4d23171cdd8b
Revises: 68348e3597f2
Create Date: 2025-02-20 08:46:21.913158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d23171cdd8b'
down_revision: Union[str, None] = '68348e3597f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'image_urls',
        type_=sa.dialects.postgresql.JSONB,
        postgresql_using="image_urls::jsonb"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'image_urls',
        type_=sa.Text(),  # Change this to the original data type
        postgresql_using="image_urls::text"
    )
    # ### end Alembic commands ###
