"""Initial migration for new DB5

Revision ID: 68348e3597f2
Revises: 82758b840162
Create Date: 2025-02-20 08:31:36.048066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68348e3597f2'
down_revision: Union[str, None] = '82758b840162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'image_urls',
        type_=sa.dialects.postgresql.JSONB,
        postgresql_using="image_urls::jsonb"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'image_urls',
        type_=sa.Text(),  # Change this to the original data type
        postgresql_using="image_urls::text"
    )
    # ### end Alembic commands ###
