"""addition of is_owner to user model

Revision ID: 6ea7e12db1bc
Revises: 84f881a0fb1f
Create Date: 2025-09-29 08:54:49.378830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea7e12db1bc'
down_revision: Union[str, None] = '84f881a0fb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_owner')
    # ### end Alembic commands ###
