"""Initial migration for new DB12

Revision ID: 7fa959f4e97c
Revises: 249e7a2b77fd
Create Date: 2025-02-21 10:49:02.956012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa959f4e97c'
down_revision: Union[str, None] = '249e7a2b77fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
