"""Initial migration for new DB4

Revision ID: 82758b840162
Revises: 0d4926609f33
Create Date: 2025-02-19 16:59:02.824787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82758b840162'
down_revision: Union[str, None] = '0d4926609f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'image_urls',
        type_=sa.dialects.postgresql.JSONB,
        postgresql_using="image_urls::jsonb"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products', 'image_urls',
        type_=sa.Text(),  # Change this to the original data type
        postgresql_using="image_urls::text"
    )
    # ### end Alembic commands ###
