"""Initial migration for new DB15

Revision ID: 84dbc6ad0cca
Revises: 3af7ce5fb598
Create Date: 2025-02-21 17:20:55.924824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dbc6ad0cca'
down_revision: Union[str, None] = '3af7ce5fb598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
