"""added alembic fields

Revision ID: 87dd96c118ff
Revises: 999bb1cf9ca1
Create Date: 2025-10-15 15:40:28.093910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dd96c118ff'
down_revision: Union[str, None] = '999bb1cf9ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('total_sales', sa.Integer(), nullable=True))
    op.add_column('shops', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('shops', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'featured')
    op.drop_column('shops', 'view_count')
    op.drop_column('shops', 'total_sales')
    # ### end Alembic commands ###
