"""update23

Revision ID: 8b8cb489fe84
Revises: 11846723c4fc
Create Date: 2025-01-08 13:13:15.858370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8cb489fe84'
down_revision: Union[str, None] = '11846723c4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.drop_constraint('appointment_doctor_id_fkey', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'appointment', ['appointment_id'], ['id'])
    op.drop_column('appointment', 'doctor_id')
    op.add_column('doctor', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doctor', 'appointment', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.drop_column('doctor', 'appointment_id')
    op.add_column('appointment', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_doctor_id_fkey', 'appointment', 'doctor', ['doctor_id'], ['id'])
    op.drop_column('appointment', 'appointment_id')
    # ### end Alembic commands ###
