"""update6

Revision ID: 948493e213cc
Revises: fd66b152961f
Create Date: 2025-01-08 13:27:15.480114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948493e213cc'
down_revision: Union[str, None] = 'fd66b152961f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctor_appointment_id_fkey', 'doctor', type_='foreignkey')
    op.drop_column('doctor', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('doctor_appointment_id_fkey', 'doctor', 'appointment', ['appointment_id'], ['id'])
    # ### end Alembic commands ###
