"""fix cart relationship

Revision ID: 999bb1cf9ca1
Revises: bf4fff3a5cc8
Create Date: 2025-09-29 14:03:48.105227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999bb1cf9ca1'
down_revision: Union[str, None] = 'bf4fff3a5cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_cart_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'cart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_cart_id_fkey', 'users', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###
