"""Initial migration for new DB10

Revision ID: 9b42e0f38f38
Revises: 0a2b7d0b0c23
Create Date: 2025-02-20 16:41:11.133586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b42e0f38f38'
down_revision: Union[str, None] = '0a2b7d0b0c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_cart_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'cart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_cart_id_fkey', 'users', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###
