"""update1

Revision ID: aa67c233af48
Revises: d5f99c9baad0
Create Date: 2025-01-08 11:37:18.521207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa67c233af48'
down_revision: Union[str, None] = 'd5f99c9baad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.alter_column('appointment', 'condition',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('patient_email_key', 'patient', type_='unique')
    op.drop_constraint('patient_username_key', 'patient', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('patient_username_key', 'patient', ['username'])
    op.create_unique_constraint('patient_email_key', 'patient', ['email'])
    op.alter_column('appointment', 'condition',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
