"""Initial migration for new DB16

Revision ID: b02a02d0ba20
Revises: 84dbc6ad0cca
Create Date: 2025-02-21 17:26:01.695767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02a02d0ba20'
down_revision: Union[str, None] = '84dbc6ad0cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
