"""Initial migration for new DB9

Revision ID: b820f7a4b4a0
Revises: 4af0aa697edc
Create Date: 2025-02-20 15:37:19.171192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b820f7a4b4a0'
down_revision: Union[str, None] = '4af0aa697edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
