"""Initial migration for new DB16

Revision ID: bc2a3498f95b
Revises: b02a02d0ba20
Create Date: 2025-02-21 17:32:32.342077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2a3498f95b'
down_revision: Union[str, None] = 'b02a02d0ba20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
