"""added cart_id on user model

Revision ID: bf4fff3a5cc8
Revises: 22b72641fe1a
Create Date: 2025-09-29 13:43:17.848227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4fff3a5cc8'
down_revision: Union[str, None] = '22b72641fe1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'cart_id')
    # ### end Alembic commands ###
