"""update

Revision ID: c0a275b4039f
Revises: 87dd96c118ff
Create Date: 2025-10-15 16:03:05.943265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a275b4039f'
down_revision: Union[str, None] = '87dd96c118ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_sales', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('featured', sa.Boolean(), nullable=True))
    op.drop_column('shops', 'view_count')
    op.drop_column('shops', 'total_sales')
    op.drop_column('shops', 'featured')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('total_sales', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'featured')
    op.drop_column('products', 'view_count')
    op.drop_column('products', 'total_sales')
    # ### end Alembic commands ###
