"""Initial migration for new DB

Revision ID: ec2eddd9f63f
Revises: 6fd0bdf3cd7a
Create Date: 2025-02-19 16:42:58.903044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2eddd9f63f'
down_revision: Union[str, None] = '6fd0bdf3cd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
