"""fix product to shop relationship bug

Revision ID: f14033aa0f94
Revises: 6ea7e12db1bc
Create Date: 2025-09-29 09:33:48.570100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14033aa0f94'
down_revision: Union[str, None] = '6ea7e12db1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
